language: android
jdk: oraclejdk7
sudo: false
cache:
  directories:
      - ${TRAVIS_BUILD_DIR}/pebble-locker-android/gradle/caches/
      - ${TRAVIS_BUILD_DIR}/pebble-locker-android/gradle/wrapper/dists/
android:
  components:
    - extra-android-support
    - extra-android-m2repository
env:
    global:
    - TERM=dumb
    - ADB_INSTALL_TIMEOUT=8
    matrix:
    - ANDROID_SDKS=android-21 ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-18 ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-17 ANDROID_TARGET=android-17 ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-16 ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-15 ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a
before_script:
    - cd pebble-locker-android
    - chmod +x gradlew
    - ./gradlew assembleDebug || true
    - ./gradlew assembleDebug || true
    - ./gradlew assembleDebug || true
    - echo no | android create avd --force -n pebbleLockerTest -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd pebbleLockerTest -no-skin -no-audio -no-window &
    - adb wait-for-device
    - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
    - adb shell input keyevent 82 &
script: ./gradlew --info :pebblelocker:connectedAndroidTest
